### ISSUE TITLE
Is the Slider module currently active/available?

### ISSUE THREAD

**Issue by designbuildtest** [BinaryMoon/wp-toolbelt#115]
Gidday Ben, is the Slider module active/available as of today, 22/10/2020? 

I've installed the WP Toolbelt plugin from GitHub, enabled the module in the WP Toolbelt admin area, but aren't seeing any new block listed in Gutenberg (I'm running the Gutenberg plugin 9.1.1).

Many thanks for all your work on WP Toolbelt, a fantastic utility plugin for us non-Jetpackers.

**Comment by designbuildtest** [comment]
Apologies Ben, I've just seen issue #96. Do you have a timeframe/possible release date for 2.8?

**Comment by BinaryMoon** [comment]
Hi there - I don't have a time frame but I don't think it'll be too long now. I'm currently testing and tweaking since there's a lot of new things in this update (I've renumbered it to v3 since there's been so many changes).

If you want to test it then you could download the dev version.
https://github.com/BinaryMoon/wp-toolbelt/archive/dev.zip

**Comment by designbuildtest** [comment]
Cheers Ben. Thank you so much for the significant time and effort you've devoted to WP Toolbelt. I'm determined to keep my WP installs JetPack-free and WP Toolbelt helps immensely. Thanks again.
