### ISSUE TITLE
Check JavaScripts too

### ISSUE THREAD

**Issue by szepeviktor** [BinaryMoon/wp-toolbelt#40]
You may look for a tool to guard JavaScript code quality.

A liberal choice is ESLint.

[JSLint](https://www.jslint.com/) will teach you how to produce robust code. (although [fiddly to use](https://github.com/reid/node-jslint/issues/170#issuecomment-531444735) on the command line)

**Comment by BinaryMoon** [comment]
Hey Viktor - I was thinking about this yesterday and I added jshint and a test to my package.json - but I wasn't sure how to install jshint and run the test:
https://github.com/BinaryMoon/wp-toolbelt/commit/5abb4a5ceafd66cc0dc3168090a4243e3a1b4f92

**Comment by BinaryMoon** [comment]
Also - I was trying to add phpstan to my WordPress theme but it kept coming up with errors about unknown functions - mostly because I've added support for plugins.

It also came up with loads of errors about argument counts.

I ended up adding rules that ignored those errors entirely but that doesn't seem like the best thing to do:
https://github.com/BinaryMoon/jarvis/blob/master/phpstan.neon.dist#L34-L39

**Comment by szepeviktor** [comment]
> but I wasn't sure how to install jshint and run the test:

`npm i && npm test` ?

**Comment by szepeviktor** [comment]
My notes are in https://github.com/BinaryMoon/jarvis/issues/59

**Comment by BinaryMoon** [comment]
Gonna close this since jshint seems to be working well
