### ISSUE TITLE
Active consent needed for tracking cookies

### ISSUE THREAD

**Issue by pixolin** [BinaryMoon/wp-toolbelt#71]
Currently Toolbelt's Cookie banner shows a message

> By using this website, you agree to our cookie policy [X]

Website visitors can only remove the message with a click on a close-icon which assumes they agree with the message. Users don't have the possibility to opt out and can't consent actively.

I'm not a lawyer, but as far as I know, this procedure isn't valid:

> … pre-checked consent boxes (or cookie banners that tell you a cookie has already been dropped and pointlessly invite you to click ‘ok’) aren’t valid under EU law.

(Source: [TechCrunch: Europe’s top court says active consent is needed for tracking cookies](https://techcrunch.com/2019/10/01/europes-top-court-says-active-consent-is-needed-for-tracking-cookies/)

**Comment by BinaryMoon** [comment]
Yes - you're totally right. I should probably add something about it being up to site owners to check the legality.

By default the plugin just adds the accept button. This is what Jetpack does. Unfortunately there's no way for me to know what cookies are set, or when they are set. I guess I could (possibly - I don't know how) delete all the cookies but I'd have no way of knowing if they were added back.

However, there is an additional button that can be activated, so that it displays 'accept' or 'decline' instead.

For this to happen you have to add a request to the 'toolbelt_cookies_accepted' filter. You can use this to hook in your javascript function that executes the functions that use cookies. There's more info here:
https://github.com/BinaryMoon/wp-toolbelt/wiki/Cookie-Banner#close-accept-decline

There's also an example of setting up Google Analytics so that it only tracks once you have pressed the accept button:
https://github.com/BinaryMoon/wp-toolbelt/wiki/Cookie-Banner#google-analytics-tracking

**Comment by pixolin** [comment]
For technically savvy users, this may be a working workaround. For all others the Cookie Banner in its current version could become a legal problem. I'm afraid, you don't offer a good service by providing this module in it's current state.
Unfortunately Jetpack is not GDPR compliant for several reasons.

Also a button to decline only seems to make sense if all relevant cookies are suppressed as a result, too.

**Comment by BinaryMoon** [comment]
Yeah - I know it's not ideal, but I am not sure how I can add a cookie bar that is GDPR compliant without some sort of developer integration. I need to be aware of every script and action that uses cookies, but there's no way to do this.

This sort of thing would be so much easier if it was implemented at the browser level rather than a site level.

> Unfortunately Jetpack is not GDPR compliant for several reasons.

That's one of the inspirations behind Toolbelt. With the addition of the form block I was able to remove Jetpack from my site yesterday. That was the last element I was relying on.

> Also a button to decline only seems to make sense if all relevant cookies are suppressed as a result, too.

I have to put some trust in site owners that they know what they are doing. If they know how to hook into a php function to make the button display then I assume they will hook everything in appropriately.

I think what I will do for now is try to make the docs clearer, and add a disclaimer in the module description saying it's not GDPR compliant by default and requires dev work to function properly. Unless you have a suggestion for how I can improve the default behaviour?

**Comment by BinaryMoon** [comment]
I've updated the docs page:
https://github.com/BinaryMoon/wp-toolbelt/wiki/Cookie-Banner

In the next release the cookie banner module will look like this:
<img width="795" alt="Screenshot 2019-11-26 at 09 36 42" src="https://user-images.githubusercontent.com/1004130/69617575-4debe000-1030-11ea-8c41-9f885ea3e1b3.png">

**Comment by pixolin** [comment]
First of all let me thank you for your immediate response.

While this disclaimer makes users aware further action is necessary, I wonder if that is a good decision regarding "marketing" of your plugin. Why offer a module that links to a privacy policy if at the same moment you concede, it wouldn't work as intended right out of the box? And isn't that, what you initially wanted: cool little helpers, that work right away and provide that little extra without much hassle?

I'm fine with closing this issue and your solution works for me. At the same time, however, I do not see the need to offer this module.

**Comment by BinaryMoon** [comment]
Thanks - that's definitely a valid concern. I don't see the problem with offering it though. Initially I made the plugin as a replacement for Jetpack. Jetpack includes a cookie consent 'widget' (why it's a widget I don't understand) and so I wanted to include one.

That said I agree it goes against my 'it just works' philosophy, and if any future developments occur (or I learn new things) that allow me to make it more compliant then I will definitely implement them. And maybe I'll remove it in the future. I don't like cookie banners and avoid them on my own sites as much as possible. It would be nice if we could remove them everywhere.

**Comment by pixolin** [comment]
It's indeed odd how some websites nag their visitors with (even unneccessary) cookie banners, privacy policy confirmation, browser notifications and newsletter subscription before you even had a chance to read a single line of their content.

Wouldn't it be cool to have a plugin check your sites for cookies to find out, if you need any cookie banner at all? (Assuming the login cookie is only provided to authorized users, only.)

**Comment by BinaryMoon** [comment]
That would be cool. I have no idea how it would work but I'll add it to the wishlist. You never know.

Things are changing in this area so maybe something will be added to browser apis in the future.
